name: Image Build Process

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
      TAG:
        required: false
        type: string
        default: "latest"
    secrets:
      HOST:
        required: true
      USERNAME:
        required: true

jobs:
  build:
    name: Docker Image Build Process
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo ${{ secrets.MVP_API_BASE_URL }}
          echo ${{ github.repository }}
          echo ${{ inputs.TAG }}
          echo ${{ inputs.ENVIRONMENT }}
          echo ${{ secrets.HOST }}
          echo ${{ inputs.HOST }}
          echo ${{ github.sha }}
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}
          echo ${{ github.actor }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.workflow }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.event.repository.name }}
          echo ${{ github.event.repository.full_name }}
          echo ${{ github.event.repository.owner.login }}
          echo ${{ github.event.repository.owner.id }}
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/app:${{ inputs.TAG }}
