name: Image Build Process

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
      TAG:
        required: false
        type: string
        default: "latest"
    secrets:
      HOST:
        required: true
      USERNAME:
        required: true

jobs:
  build:
    name: Docker Image Build Process
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          fetch-depth: 0
          submodules: true

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.ORG_SEC_DOCKER_USERNAME }}
      #     password: ${{ secrets.ORG_SEC_DOCKER_TOKEN }}
      - name: Checkout code
        run: |
          echo Input Tag ${{ inputs.TAG }}
          echo Input Environment ${{ inputs.ENVIRONMENT }}
          echo Action Actor ${{ github.actor }}
          echo Action Run Number ${{ github.run_number }}
          echo Repository Name ${{ github.event.repository.full_name }}
          echo Input Host ${{ inputs.HOST }}
          echo Input Host ${{ secrets.HOST }}
        shell: bash
      - name: environment variables
        run: |
          touch .env
          echo "ENV_HTTP_PROXY=${{ vars.ENV_HTTP_PROXY }}" >> .env
          echo "REPO_ENV_HTTP_PROXY=${{ vars.REPO_ENV_HTTP_PROXY }}" >> .env
          echo "ORG_ENV_HTTP_PROXY=${{ vars.ORG_ENV_HTTP_PROXY }}" >> .env
          echo "SEC_HTTP_PROXY=${{ secrets.SEC_HTTP_PROXY }}" >> .env
          echo "REPO_SEC_HTTP_PROXY=${{ secrets.REPO_SEC_HTTP_PROXY }}" >> .env
          echo "ORG_SEC_HTTP_PROXY=${{ secrets.ORG_SEC_HTTP_PROXY }}" >> .env
          echo "ORG_SEC_DOCKER_USERNAME=${{ secrets.ORG_SEC_DOCKER_USERNAME }}" >> .env
          echo "ORG_SEC_DOCKER_TOKEN=${{ secrets.ORG_SEC_DOCKER_TOKEN }}" >> .env
          echo "ENVIRONMENT=${{ inputs.ENVIRONMENT }}" >> .env
          echo "TAG=${{ inputs.TAG }}" >> .env
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "GITHUB_ACTOR=${{ github.actor }}" >> .env
          echo "GITHUB_RUN_NUMBER=${{ github.run_number }}" >> .env
          echo "GITHUB_REPOSITORY=${{ github.event.repository.full_name }}" >> .env
          echo "GITHUB_REPOSITORY_OWNER=${{ github.event.repository.owner.login }}" >> .env
          echo "GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }}" >> .env
          cat .env
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ravenkaisar/email-notifications-ms:${{ inputs.TAG }}
