name: Image Build Process

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
      TAG:
        required: false
        type: string
        default: "latest"
    secrets:
      HOST:
        required: true
      USERNAME:
        required: true

jobs:
  build:
    name: Docker Image Build Process
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo Input Tag ${{ inputs.TAG }}
          echo Input Environment ${{ inputs.ENVIRONMENT }}
          echo Action Actor ${{ github.actor }}
          echo Action Run Number ${{ github.run_number }}
          echo Repository Name ${{ github.event.repository.full_name }}
          echo Input Host ${{ inputs.HOST }}
          echo Input Host ${{ secrets.HOST }}
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          fetch-depth: 0
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/app:${{ inputs.TAG }}
